WebApplication2/Models/KhuyenMai.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhuyenMai()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public string Makhuyenmai { get; set; }
        public string Maloai { get; set; }
        public Nullable<int> Mucgiam { get; set; }
        public string MaApDung { get; set; }
        public Nullable<int> GTapdung { get; set; }
        public Nullable<System.DateTime> TGbatdau { get; set; }
        public Nullable<System.DateTime> TGketthuc { get; set; }
    
        public virtual LoaiApDung LoaiApDung { get; set; }
        public virtual LoaiKhuyenMai LoaiKhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}

WebApplication2/Controllers/KhuyenMaisController.cs
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Transactions;
using WebApplication2.Models;
using Microsoft.AspNet.Identity;

namespace WebApplication2.Controllers
{
    public class KhuyenMaisController : Controller
    {
        private CT25Team17Entities db = new CT25Team17Entities();

        [Authorize(Roles = "Admin")]
        // GET: KhuyenMais
        public ActionResult Index()
        {
            var khuyenMais = db.KhuyenMais.Include(k => k.LoaiApDung).Include(k => k.LoaiKhuyenMai);
            return View(khuyenMais.ToList());
        }

        // GET: KhuyenMais/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuyenMai khuyenMai = db.KhuyenMais.Find(id);
            if (khuyenMai == null)
            {
                return HttpNotFound();
            }
            return View(khuyenMai);
        }

        // GET: KhuyenMais/Create
        public ActionResult Create()
        {
            ViewBag.MaApDung = new SelectList(db.LoaiApDungs, "MaApDung", "TenLApDung");
            ViewBag.MaApDung = new SelectList(db.LoaiApDungs, "MaApDung", "TenLApDung");
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai");
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai");
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai");
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai");
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai");
            return View();
        }

        // POST: KhuyenMais/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(KhuyenMai khuyenMai)
        {
            CheckThongTinCreate(khuyenMai);
            if (ModelState.IsValid)
            {
                db.KhuyenMais.Add(khuyenMai);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaApDung = new SelectList(db.LoaiApDungs, "MaApDung", "TenLApDung", khuyenMai.MaApDung);
            ViewBag.MaApDung = new SelectList(db.LoaiApDungs, "MaApDung", "TenLApDung", khuyenMai.MaApDung);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            return View(khuyenMai);
        }

        private void CheckThongTinCreate(KhuyenMai khuyenMai)
        {
            var regexItem = new Regex("^[ a-z A-Z 0-9 ]*$");
            var regexNumeric = new Regex("^[ 0-9 ]*$");
            var regexWord = new Regex("^[ a-z A-Z ]*$");
            //Kiem tra MaSP
            foreach (var item in db.KhuyenMais)
            {
                if (khuyenMai.Makhuyenmai == item.Makhuyenmai)
                {
                    ModelState.AddModelError("Makhuyenmai", "Mã khuyến mãi đã tồn tại.");
                }
            }
            if (khuyenMai.Makhuyenmai == null)
            {
                ModelState.AddModelError("Makhuyenmai", "Mã khuyến mãi không được để trống.");
            }
            else
            {
                if (khuyenMai.Makhuyenmai.Length != 10)
                {
                    ModelState.AddModelError("Makhuyenmai", "Mã khuyến mãi phải có đúng 10 ký tự.");
                }
                else
                {
                    if (khuyenMai.Makhuyenmai.IndexOf(" ") >= 0)
                    {
                        ModelState.AddModelError("Makhuyenmai", "Mã khuyến mãi không chứa khoảng trắng.");
                    }
                    else
                    {
                        if (regexItem.IsMatch(khuyenMai.Makhuyenmai) == false)
                        {
                            ModelState.AddModelError("Makhuyenmai", "Mã khuyến mãi chỉ chứa ký tự alphabet(a-z,A-Z,0-9).");
                        }
                    }
                }
            }

            // Loại khuyến mãi và mức giảm giá
            if (khuyenMai.Mucgiam == null)
            {
                ModelState.AddModelError("Mucgiam", "Mức giảm giá không được rỗng.");
            }
            else
            {
                if (khuyenMai.Maloai.ToString() == "KML-02")
                {
                    if(khuyenMai.Mucgiam < 1 || khuyenMai.Mucgiam > 100)
                    {
                        ModelState.AddModelError("Mucgiam", "Mức giảm giá theo % có giá trị từ 1-100%");
                    }
                }
                else
                {
                    if(khuyenMai.Mucgiam < 1)
                    {
                        ModelState.AddModelError("Mucgiam", "Mức giảm giá phải lớn hơn 1");
                    }
                }
            }

            // Loại áp dụng và giá trị tối thiểu
            if (khuyenMai.MaApDung.ToString() == "KMAD-01")
            {
                khuyenMai.GTapdung = null;
            }
            else
            {
                if(khuyenMai.GTapdung <1)
                {
                    ModelState.AddModelError("GTapdung", "Giá trị áp dụng phải lớn hơn 1");
                }
                else if(khuyenMai.GTapdung < khuyenMai.Mucgiam)
                {
                    ModelState.AddModelError("GTapdung", "Giá trị áp dụng phải lớn hơn mức giảm giá");
                }
                else if(khuyenMai.GTapdung == null)
                {
                    ModelState.AddModelError("GTapdung", "Giá trị áp dụng không được bỏ trống");
                }
                else { }
            }

            // Thời gian có event
            if(khuyenMai.TGbatdau == null)
            {
                ModelState.AddModelError("TGbatdau", "Thời gian bắt đầu khuyến mãi không được trống");
            }
            else if(khuyenMai.TGketthuc == null)
            {
                ModelState.AddModelError("TGketthuc", "Thời gian kết thúc khuyến mãi không được trống");
            }
            else
            {
                string[] time1 = khuyenMai.TGbatdau.ToString().Split('/');
                string[] year1 = time1[2].Split(' ');
                string[] time2 = khuyenMai.TGketthuc.ToString().Split('/');
                string[] year2 = time2[2].Split(' ');
                DateTime date1 = new DateTime(int.Parse(year1[0]), int.Parse(time1[0]),int.Parse(time1[1]),0,0,0);
                DateTime date2 = new DateTime(int.Parse(year2[0]), int.Parse(time2[0]), int.Parse(time2[1]), 0, 0, 0);
                int result = DateTime.Compare(date1, date2);
                string relationship;

                if (result < 0) { }
                else if (result == 0)
                    ModelState.AddModelError("TGketthuc", "Thời gian kết thúc khuyến mãi không trùng với thời gian bắt đầu");
                else
                    ModelState.AddModelError("TGketthuc", "Thời gian kết thúc khuyến mãi sau thời gian bắt đầu");

            }
        }
            // GET: KhuyenMais/Edit/5
        public ActionResult Edit(string id)
            {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhuyenMai khuyenMai = db.KhuyenMais.Find(id);
            if (khuyenMai == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaApDung = new SelectList(db.LoaiApDungs, "MaApDung", "TenLApDung", khuyenMai.MaApDung);
            ViewBag.MaApDung = new SelectList(db.LoaiApDungs, "MaApDung", "TenLApDung", khuyenMai.MaApDung);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            return View(khuyenMai);
        }

        // POST: KhuyenMais/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Makhuyenmai,Maloai,Mucgiam,MaApDung,GTapdung,TGbatdau,TGketthuc")] KhuyenMai khuyenMai)
        {
            if (ModelState.IsValid)
            {
                db.Entry(khuyenMai).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaApDung = new SelectList(db.LoaiApDungs, "MaApDung", "TenLApDung", khuyenMai.MaApDung);
            ViewBag.MaApDung = new SelectList(db.LoaiApDungs, "MaApDung", "TenLApDung", khuyenMai.MaApDung);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);
            ViewBag.Maloai = new SelectList(db.LoaiKhuyenMais, "Maloai", "Tenloai", khuyenMai.Maloai);

WebApplication2/Views/KhuyenMais/Delete.cshtml
@model WebApplication2.Models.KhuyenMai

@{
    ViewBag.Title = "Delete";
}


<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Thông báo xác nhận xóa!</h4>
                <div class="ms-auto text-end">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="@Url.Action("Index","KhuyenMais")">Danh sách mã khuyến mãi</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Tạo mã khuyến mãi</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card" align="center">
                    <div class="card-body" align="center">
                        <h3>Bạn có chắc muốn xóa?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-actions no-color">
                                <input type="submit" value="Xóa" class="btn btn-default" />
                                <a href="@Url.Action("Index", "KhuyenMais")">
                                    <button type="button" class="btn btn-secondary"
                                            style="margin-left: 15px;">
                                        Hủy
                                    </button>
                                </a>
                            </div>
                        }
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End PAge Content -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Right sidebar -->
            <!-- ============================================================== -->
            <!-- .right-sidebar -->
            <!-- ============================================================== -->
            <!-- End Right sidebar -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer text-center">
            All Rights Reserved by Matrix-admin. Designed and Developed by <a href="https://www.wrappixel.com">WrapPixel</a>.
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
</div>

@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KhuyenMai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mucgiam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mucgiam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GTapdung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GTapdung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TGbatdau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TGbatdau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TGketthuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TGketthuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiApDung.TenLApDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiApDung.TenLApDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiKhuyenMai.Tenloai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiKhuyenMai.Tenloai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
*@

WebApplication2/Views/KhuyenMais/Index.cshtml
@model IEnumerable<WebApplication2.Models.KhuyenMai>

@{
    ViewBag.Title = "Index";
}

<!-- Page wrapper  -->
<!-- ============================================================== -->
<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
                <h4 class="page-title">Danh sách mã khuyến mãi</h4>
                <div class="ms-auto text-end">
                    <nav aria-label="breadcrumb">
                        <button type="button" class="btn btn-primary" style="margin-bottom: 5px;"><a href="@Url.Action("Create","KhuyenMais")" style="text-decoration: none; color: #fff;">Tạo mới mã khuyến mãi</a></button>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">Danh sách mã khuyến mãi</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Danh sách mã khuyến mãi</h5>
                        <div class="table-responsive">
                            <table id="zero_config" class="table table-striped table-bordered">
                                <thead>
                                    <tr align="center">
                                        <th scope="col">Mã khuyến mãi</th>
                                        <th scope="col">Loại khuyến mãi</th>
                                        <th scope="col">Mức giảm</th>
                                        <th scope="col">Áp dụng cho</th>
                                        <th scope="col">Trị giá từ</th>
                                        <th scope="col">Thời gian bắt đầu</th>
                                        <th scope="col">Thời gian kết thúc</th>
                                        <th scope="col">Xóa</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr align="center">
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Makhuyenmai)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.LoaiKhuyenMai.Tenloai)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Mucgiam)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.LoaiApDung.TenLApDung)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.GTapdung)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TGbatdau)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TGketthuc)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Delete", "Delete", new { id = item.Makhuyenmai })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center">
        All Rights Reserved by Matrix-admin. Designed and Developed by <a href="https://www.wrappixel.com">WrapPixel</a>.
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
    </div>
</div>
@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Makhuyenmai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LoaiKhuyenMai.Tenloai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mucgiam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LoaiApDung.TenLApDung)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GTapdung)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TGbatdau)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TGketthuc)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Makhuyenmai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoaiKhuyenMai.Tenloai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mucgiam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoaiApDung.TenLApDung)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GTapdung)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TGbatdau)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TGketthuc)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

    </table>
*@